/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface MenuItemInputWithAvailability {
    name: string;
    description: string;
    available: boolean;
    imageUrl: string;
    prepTime: bigint;
    category: string;
    price: bigint;
    foodType: FoodType;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface RestaurantInput {
    name: string;
    cuisineType: CuisineType;
    logoUrl: string;
    address: string;
    openingHours: OpeningHours;
    avgPrepTime: bigint;
}
export interface Order {
    id: string;
    status: OrderStatus;
    user: Principal;
    timestamp: Time;
    items: Array<CartItem>;
    totalPrice: bigint;
    restaurant: Restaurant;
}
export interface Restaurant {
    id: string;
    menu: Array<MenuItem>;
    name: string;
    cuisineType: CuisineType;
    logoUrl: string;
    address: string;
    openingHours: OpeningHours;
    avgPrepTime: bigint;
}
export interface OpeningHours {
    openingTime: string;
    closingTime: string;
}
export interface MenuItem {
    id: string;
    name: string;
    description: string;
    available: boolean;
    imageUrl: string;
    prepTime: bigint;
    category: string;
    price: bigint;
    foodType: FoodType;
}
export interface Cart {
    total: bigint;
    platformFee: bigint;
    deliveryCharges: bigint;
    items: Array<CartItem>;
    subtotal: bigint;
}
export interface CartItem {
    item: MenuItem;
    quantity: bigint;
}
export interface UserProfile {
    name: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum CuisineType {
    mediterranean = "mediterranean",
    japanese = "japanese",
    chinese = "chinese",
    mexican = "mexican",
    italian = "italian",
    indian = "indian",
    american = "american"
}
export enum FoodType {
    veg = "veg",
    dessert = "dessert",
    nonVeg = "nonVeg",
    snack = "snack",
    beverage = "beverage"
}
export enum OrderStatus {
    preparing = "preparing",
    outForDelivery = "outForDelivery",
    delivered = "delivered",
    confirmed = "confirmed"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addMenuItem(restaurantId: string, itemInput: MenuItemInputWithAvailability): Promise<MenuItem>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    calculateCart(items: Array<CartItem>): Promise<Cart>;
    filterMenuByFoodType(restaurantId: string, foodType: FoodType): Promise<Array<MenuItem>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getOrder(orderId: string): Promise<Order | null>;
    getOrderHistory(): Promise<Array<Order>>;
    getRestaurantById(restaurantId: string): Promise<Restaurant | null>;
    getRestaurantMenu(restaurantId: string): Promise<Array<MenuItem>>;
    getRestaurants(): Promise<Array<Restaurant>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initSampleData(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    placeOrder(restaurantId: string, items: Array<CartItem>): Promise<string>;
    registerRestaurant(input: RestaurantInput): Promise<Restaurant>;
    resyncOrderStatuses(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateOrderStatus(orderId: string, newStatus: OrderStatus): Promise<void>;
}
import type { Cart as _Cart, CartItem as _CartItem, CuisineType as _CuisineType, FoodType as _FoodType, MenuItem as _MenuItem, MenuItemInputWithAvailability as _MenuItemInputWithAvailability, OpeningHours as _OpeningHours, Order as _Order, OrderStatus as _OrderStatus, Restaurant as _Restaurant, RestaurantInput as _RestaurantInput, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addMenuItem(arg0: string, arg1: MenuItemInputWithAvailability): Promise<MenuItem> {
        if (this.processError) {
            try {
                const result = await this.actor.addMenuItem(arg0, to_candid_MenuItemInputWithAvailability_n8(this._uploadFile, this._downloadFile, arg1));
                return from_candid_MenuItem_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMenuItem(arg0, to_candid_MenuItemInputWithAvailability_n8(this._uploadFile, this._downloadFile, arg1));
            return from_candid_MenuItem_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n16(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n16(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async calculateCart(arg0: Array<CartItem>): Promise<Cart> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateCart(to_candid_vec_n18(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Cart_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateCart(to_candid_vec_n18(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Cart_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterMenuByFoodType(arg0: string, arg1: FoodType): Promise<Array<MenuItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterMenuByFoodType(arg0, to_candid_FoodType_n10(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterMenuByFoodType(arg0, to_candid_FoodType_n10(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrder(arg0: string): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrderHistory(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrderHistory();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrderHistory();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRestaurantById(arg0: string): Promise<Restaurant | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRestaurantById(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRestaurantById(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRestaurantMenu(arg0: string): Promise<Array<MenuItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRestaurantMenu(arg0);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRestaurantMenu(arg0);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRestaurants(): Promise<Array<Restaurant>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRestaurants();
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRestaurants();
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async initSampleData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initSampleData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initSampleData();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async placeOrder(arg0: string, arg1: Array<CartItem>): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(arg0, to_candid_vec_n18(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(arg0, to_candid_vec_n18(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async registerRestaurant(arg0: RestaurantInput): Promise<Restaurant> {
        if (this.processError) {
            try {
                const result = await this.actor.registerRestaurant(to_candid_RestaurantInput_n44(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Restaurant_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerRestaurant(to_candid_RestaurantInput_n44(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Restaurant_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async resyncOrderStatuses(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resyncOrderStatuses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resyncOrderStatuses();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateOrderStatus(arg0: string, arg1: OrderStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n48(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n48(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_CartItem_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CartItem): CartItem {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Cart_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cart): Cart {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_CuisineType_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CuisineType): CuisineType {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_FoodType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FoodType): FoodType {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_MenuItem_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MenuItem): MenuItem {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Restaurant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Restaurant): Restaurant {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n33(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Restaurant]): Restaurant | null {
    return value.length === 0 ? null : from_candid_Restaurant_n37(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    description: string;
    available: boolean;
    imageUrl: string;
    prepTime: bigint;
    category: string;
    price: bigint;
    foodType: _FoodType;
}): {
    id: string;
    name: string;
    description: string;
    available: boolean;
    imageUrl: string;
    prepTime: bigint;
    category: string;
    price: bigint;
    foodType: FoodType;
} {
    return {
        id: value.id,
        name: value.name,
        description: value.description,
        available: value.available,
        imageUrl: value.imageUrl,
        prepTime: value.prepTime,
        category: value.category,
        price: value.price,
        foodType: from_candid_FoodType_n14(_uploadFile, _downloadFile, value.foodType)
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    platformFee: bigint;
    deliveryCharges: bigint;
    items: Array<_CartItem>;
    subtotal: bigint;
}): {
    total: bigint;
    platformFee: bigint;
    deliveryCharges: bigint;
    items: Array<CartItem>;
    subtotal: bigint;
} {
    return {
        total: value.total,
        platformFee: value.platformFee,
        deliveryCharges: value.deliveryCharges,
        items: from_candid_vec_n25(_uploadFile, _downloadFile, value.items),
        subtotal: value.subtotal
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    item: _MenuItem;
    quantity: bigint;
}): {
    item: MenuItem;
    quantity: bigint;
} {
    return {
        item: from_candid_MenuItem_n12(_uploadFile, _downloadFile, value.item),
        quantity: value.quantity
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _OrderStatus;
    user: Principal;
    timestamp: _Time;
    items: Array<_CartItem>;
    totalPrice: bigint;
    restaurant: _Restaurant;
}): {
    id: string;
    status: OrderStatus;
    user: Principal;
    timestamp: Time;
    items: Array<CartItem>;
    totalPrice: bigint;
    restaurant: Restaurant;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n35(_uploadFile, _downloadFile, value.status),
        user: value.user,
        timestamp: value.timestamp,
        items: from_candid_vec_n25(_uploadFile, _downloadFile, value.items),
        totalPrice: value.totalPrice,
        restaurant: from_candid_Restaurant_n37(_uploadFile, _downloadFile, value.restaurant)
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    menu: Array<_MenuItem>;
    name: string;
    cuisineType: _CuisineType;
    logoUrl: string;
    address: string;
    openingHours: _OpeningHours;
    avgPrepTime: bigint;
}): {
    id: string;
    menu: Array<MenuItem>;
    name: string;
    cuisineType: CuisineType;
    logoUrl: string;
    address: string;
    openingHours: OpeningHours;
    avgPrepTime: bigint;
} {
    return {
        id: value.id,
        menu: from_candid_vec_n28(_uploadFile, _downloadFile, value.menu),
        name: value.name,
        cuisineType: from_candid_CuisineType_n39(_uploadFile, _downloadFile, value.cuisineType),
        logoUrl: value.logoUrl,
        address: value.address,
        openingHours: value.openingHours,
        avgPrepTime: value.avgPrepTime
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    veg: null;
} | {
    dessert: null;
} | {
    nonVeg: null;
} | {
    snack: null;
} | {
    beverage: null;
}): FoodType {
    return "veg" in value ? FoodType.veg : "dessert" in value ? FoodType.dessert : "nonVeg" in value ? FoodType.nonVeg : "snack" in value ? FoodType.snack : "beverage" in value ? FoodType.beverage : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    preparing: null;
} | {
    outForDelivery: null;
} | {
    delivered: null;
} | {
    confirmed: null;
}): OrderStatus {
    return "preparing" in value ? OrderStatus.preparing : "outForDelivery" in value ? OrderStatus.outForDelivery : "delivered" in value ? OrderStatus.delivered : "confirmed" in value ? OrderStatus.confirmed : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mediterranean: null;
} | {
    japanese: null;
} | {
    chinese: null;
} | {
    mexican: null;
} | {
    italian: null;
} | {
    indian: null;
} | {
    american: null;
}): CuisineType {
    return "mediterranean" in value ? CuisineType.mediterranean : "japanese" in value ? CuisineType.japanese : "chinese" in value ? CuisineType.chinese : "mexican" in value ? CuisineType.mexican : "italian" in value ? CuisineType.italian : "indian" in value ? CuisineType.indian : "american" in value ? CuisineType.american : value;
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CartItem>): Array<CartItem> {
    return value.map((x)=>from_candid_CartItem_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MenuItem>): Array<MenuItem> {
    return value.map((x)=>from_candid_MenuItem_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n33(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Restaurant>): Array<Restaurant> {
    return value.map((x)=>from_candid_Restaurant_n37(_uploadFile, _downloadFile, x));
}
function to_candid_CartItem_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CartItem): _CartItem {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_CuisineType_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CuisineType): _CuisineType {
    return to_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function to_candid_FoodType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FoodType): _FoodType {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_MenuItemInputWithAvailability_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MenuItemInputWithAvailability): _MenuItemInputWithAvailability {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_MenuItem_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MenuItem): _MenuItem {
    return to_candid_record_n22(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function to_candid_RestaurantInput_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RestaurantInput): _RestaurantInput {
    return to_candid_record_n45(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    item: MenuItem;
    quantity: bigint;
}): {
    item: _MenuItem;
    quantity: bigint;
} {
    return {
        item: to_candid_MenuItem_n21(_uploadFile, _downloadFile, value.item),
        quantity: value.quantity
    };
}
function to_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    description: string;
    available: boolean;
    imageUrl: string;
    prepTime: bigint;
    category: string;
    price: bigint;
    foodType: FoodType;
}): {
    id: string;
    name: string;
    description: string;
    available: boolean;
    imageUrl: string;
    prepTime: bigint;
    category: string;
    price: bigint;
    foodType: _FoodType;
} {
    return {
        id: value.id,
        name: value.name,
        description: value.description,
        available: value.available,
        imageUrl: value.imageUrl,
        prepTime: value.prepTime,
        category: value.category,
        price: value.price,
        foodType: to_candid_FoodType_n10(_uploadFile, _downloadFile, value.foodType)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    cuisineType: CuisineType;
    logoUrl: string;
    address: string;
    openingHours: OpeningHours;
    avgPrepTime: bigint;
}): {
    name: string;
    cuisineType: _CuisineType;
    logoUrl: string;
    address: string;
    openingHours: _OpeningHours;
    avgPrepTime: bigint;
} {
    return {
        name: value.name,
        cuisineType: to_candid_CuisineType_n46(_uploadFile, _downloadFile, value.cuisineType),
        logoUrl: value.logoUrl,
        address: value.address,
        openingHours: value.openingHours,
        avgPrepTime: value.avgPrepTime
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    description: string;
    available: boolean;
    imageUrl: string;
    prepTime: bigint;
    category: string;
    price: bigint;
    foodType: FoodType;
}): {
    name: string;
    description: string;
    available: boolean;
    imageUrl: string;
    prepTime: bigint;
    category: string;
    price: bigint;
    foodType: _FoodType;
} {
    return {
        name: value.name,
        description: value.description,
        available: value.available,
        imageUrl: value.imageUrl,
        prepTime: value.prepTime,
        category: value.category,
        price: value.price,
        foodType: to_candid_FoodType_n10(_uploadFile, _downloadFile, value.foodType)
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FoodType): {
    veg: null;
} | {
    dessert: null;
} | {
    nonVeg: null;
} | {
    snack: null;
} | {
    beverage: null;
} {
    return value == FoodType.veg ? {
        veg: null
    } : value == FoodType.dessert ? {
        dessert: null
    } : value == FoodType.nonVeg ? {
        nonVeg: null
    } : value == FoodType.snack ? {
        snack: null
    } : value == FoodType.beverage ? {
        beverage: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CuisineType): {
    mediterranean: null;
} | {
    japanese: null;
} | {
    chinese: null;
} | {
    mexican: null;
} | {
    italian: null;
} | {
    indian: null;
} | {
    american: null;
} {
    return value == CuisineType.mediterranean ? {
        mediterranean: null
    } : value == CuisineType.japanese ? {
        japanese: null
    } : value == CuisineType.chinese ? {
        chinese: null
    } : value == CuisineType.mexican ? {
        mexican: null
    } : value == CuisineType.italian ? {
        italian: null
    } : value == CuisineType.indian ? {
        indian: null
    } : value == CuisineType.american ? {
        american: null
    } : value;
}
function to_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    preparing: null;
} | {
    outForDelivery: null;
} | {
    delivered: null;
} | {
    confirmed: null;
} {
    return value == OrderStatus.preparing ? {
        preparing: null
    } : value == OrderStatus.outForDelivery ? {
        outForDelivery: null
    } : value == OrderStatus.delivered ? {
        delivered: null
    } : value == OrderStatus.confirmed ? {
        confirmed: null
    } : value;
}
function to_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<CartItem>): Array<_CartItem> {
    return value.map((x)=>to_candid_CartItem_n19(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
