/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cart {
  'total' : bigint,
  'platformFee' : bigint,
  'deliveryCharges' : bigint,
  'items' : Array<CartItem>,
  'subtotal' : bigint,
}
export interface CartItem { 'item' : MenuItem, 'quantity' : bigint }
export type CuisineType = { 'mediterranean' : null } |
  { 'japanese' : null } |
  { 'chinese' : null } |
  { 'mexican' : null } |
  { 'italian' : null } |
  { 'indian' : null } |
  { 'american' : null };
export type FoodType = { 'veg' : null } |
  { 'dessert' : null } |
  { 'nonVeg' : null } |
  { 'snack' : null } |
  { 'beverage' : null };
export interface MenuItem {
  'id' : string,
  'name' : string,
  'description' : string,
  'available' : boolean,
  'imageUrl' : string,
  'prepTime' : bigint,
  'category' : string,
  'price' : bigint,
  'foodType' : FoodType,
}
export interface MenuItemInputWithAvailability {
  'name' : string,
  'description' : string,
  'available' : boolean,
  'imageUrl' : string,
  'prepTime' : bigint,
  'category' : string,
  'price' : bigint,
  'foodType' : FoodType,
}
export interface OpeningHours { 'openingTime' : string, 'closingTime' : string }
export interface Order {
  'id' : string,
  'status' : OrderStatus,
  'user' : Principal,
  'timestamp' : Time,
  'items' : Array<CartItem>,
  'totalPrice' : bigint,
  'restaurant' : Restaurant,
}
export type OrderStatus = { 'preparing' : null } |
  { 'outForDelivery' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null };
export interface Restaurant {
  'id' : string,
  'menu' : Array<MenuItem>,
  'name' : string,
  'cuisineType' : CuisineType,
  'logoUrl' : string,
  'address' : string,
  'openingHours' : OpeningHours,
  'avgPrepTime' : bigint,
}
export interface RestaurantInput {
  'name' : string,
  'cuisineType' : CuisineType,
  'logoUrl' : string,
  'address' : string,
  'openingHours' : OpeningHours,
  'avgPrepTime' : bigint,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMenuItem' : ActorMethod<
    [string, MenuItemInputWithAvailability],
    MenuItem
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculateCart' : ActorMethod<[Array<CartItem>], Cart>,
  'filterMenuByFoodType' : ActorMethod<[string, FoodType], Array<MenuItem>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOrder' : ActorMethod<[string], [] | [Order]>,
  'getOrderHistory' : ActorMethod<[], Array<Order>>,
  'getRestaurantById' : ActorMethod<[string], [] | [Restaurant]>,
  'getRestaurantMenu' : ActorMethod<[string], Array<MenuItem>>,
  'getRestaurants' : ActorMethod<[], Array<Restaurant>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initSampleData' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[string, Array<CartItem>], string>,
  'registerRestaurant' : ActorMethod<[RestaurantInput], Restaurant>,
  'resyncOrderStatuses' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateOrderStatus' : ActorMethod<[string, OrderStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];