/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const FoodType = IDL.Variant({
  'veg' : IDL.Null,
  'dessert' : IDL.Null,
  'nonVeg' : IDL.Null,
  'snack' : IDL.Null,
  'beverage' : IDL.Null,
});
export const MenuItemInputWithAvailability = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'prepTime' : IDL.Nat,
  'category' : IDL.Text,
  'price' : IDL.Nat,
  'foodType' : FoodType,
});
export const MenuItem = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'prepTime' : IDL.Nat,
  'category' : IDL.Text,
  'price' : IDL.Nat,
  'foodType' : FoodType,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CartItem = IDL.Record({ 'item' : MenuItem, 'quantity' : IDL.Nat });
export const Cart = IDL.Record({
  'total' : IDL.Nat,
  'platformFee' : IDL.Nat,
  'deliveryCharges' : IDL.Nat,
  'items' : IDL.Vec(CartItem),
  'subtotal' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const OrderStatus = IDL.Variant({
  'preparing' : IDL.Null,
  'outForDelivery' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Time = IDL.Int;
export const CuisineType = IDL.Variant({
  'mediterranean' : IDL.Null,
  'japanese' : IDL.Null,
  'chinese' : IDL.Null,
  'mexican' : IDL.Null,
  'italian' : IDL.Null,
  'indian' : IDL.Null,
  'american' : IDL.Null,
});
export const OpeningHours = IDL.Record({
  'openingTime' : IDL.Text,
  'closingTime' : IDL.Text,
});
export const Restaurant = IDL.Record({
  'id' : IDL.Text,
  'menu' : IDL.Vec(MenuItem),
  'name' : IDL.Text,
  'cuisineType' : CuisineType,
  'logoUrl' : IDL.Text,
  'address' : IDL.Text,
  'openingHours' : OpeningHours,
  'avgPrepTime' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'status' : OrderStatus,
  'user' : IDL.Principal,
  'timestamp' : Time,
  'items' : IDL.Vec(CartItem),
  'totalPrice' : IDL.Nat,
  'restaurant' : Restaurant,
});
export const RestaurantInput = IDL.Record({
  'name' : IDL.Text,
  'cuisineType' : CuisineType,
  'logoUrl' : IDL.Text,
  'address' : IDL.Text,
  'openingHours' : OpeningHours,
  'avgPrepTime' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMenuItem' : IDL.Func(
      [IDL.Text, MenuItemInputWithAvailability],
      [MenuItem],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculateCart' : IDL.Func([IDL.Vec(CartItem)], [Cart], ['query']),
  'filterMenuByFoodType' : IDL.Func(
      [IDL.Text, FoodType],
      [IDL.Vec(MenuItem)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
  'getOrderHistory' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getRestaurantById' : IDL.Func([IDL.Text], [IDL.Opt(Restaurant)], ['query']),
  'getRestaurantMenu' : IDL.Func([IDL.Text], [IDL.Vec(MenuItem)], ['query']),
  'getRestaurants' : IDL.Func([], [IDL.Vec(Restaurant)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initSampleData' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func([IDL.Text, IDL.Vec(CartItem)], [IDL.Text], []),
  'registerRestaurant' : IDL.Func([RestaurantInput], [Restaurant], []),
  'resyncOrderStatuses' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const FoodType = IDL.Variant({
    'veg' : IDL.Null,
    'dessert' : IDL.Null,
    'nonVeg' : IDL.Null,
    'snack' : IDL.Null,
    'beverage' : IDL.Null,
  });
  const MenuItemInputWithAvailability = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'prepTime' : IDL.Nat,
    'category' : IDL.Text,
    'price' : IDL.Nat,
    'foodType' : FoodType,
  });
  const MenuItem = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'prepTime' : IDL.Nat,
    'category' : IDL.Text,
    'price' : IDL.Nat,
    'foodType' : FoodType,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CartItem = IDL.Record({ 'item' : MenuItem, 'quantity' : IDL.Nat });
  const Cart = IDL.Record({
    'total' : IDL.Nat,
    'platformFee' : IDL.Nat,
    'deliveryCharges' : IDL.Nat,
    'items' : IDL.Vec(CartItem),
    'subtotal' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const OrderStatus = IDL.Variant({
    'preparing' : IDL.Null,
    'outForDelivery' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Time = IDL.Int;
  const CuisineType = IDL.Variant({
    'mediterranean' : IDL.Null,
    'japanese' : IDL.Null,
    'chinese' : IDL.Null,
    'mexican' : IDL.Null,
    'italian' : IDL.Null,
    'indian' : IDL.Null,
    'american' : IDL.Null,
  });
  const OpeningHours = IDL.Record({
    'openingTime' : IDL.Text,
    'closingTime' : IDL.Text,
  });
  const Restaurant = IDL.Record({
    'id' : IDL.Text,
    'menu' : IDL.Vec(MenuItem),
    'name' : IDL.Text,
    'cuisineType' : CuisineType,
    'logoUrl' : IDL.Text,
    'address' : IDL.Text,
    'openingHours' : OpeningHours,
    'avgPrepTime' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'status' : OrderStatus,
    'user' : IDL.Principal,
    'timestamp' : Time,
    'items' : IDL.Vec(CartItem),
    'totalPrice' : IDL.Nat,
    'restaurant' : Restaurant,
  });
  const RestaurantInput = IDL.Record({
    'name' : IDL.Text,
    'cuisineType' : CuisineType,
    'logoUrl' : IDL.Text,
    'address' : IDL.Text,
    'openingHours' : OpeningHours,
    'avgPrepTime' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMenuItem' : IDL.Func(
        [IDL.Text, MenuItemInputWithAvailability],
        [MenuItem],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculateCart' : IDL.Func([IDL.Vec(CartItem)], [Cart], ['query']),
    'filterMenuByFoodType' : IDL.Func(
        [IDL.Text, FoodType],
        [IDL.Vec(MenuItem)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
    'getOrderHistory' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getRestaurantById' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Restaurant)],
        ['query'],
      ),
    'getRestaurantMenu' : IDL.Func([IDL.Text], [IDL.Vec(MenuItem)], ['query']),
    'getRestaurants' : IDL.Func([], [IDL.Vec(Restaurant)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initSampleData' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func([IDL.Text, IDL.Vec(CartItem)], [IDL.Text], []),
    'registerRestaurant' : IDL.Func([RestaurantInput], [Restaurant], []),
    'resyncOrderStatuses' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };